TebLocalPlannerROS:

 odom_topic: /odometry/filtered
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.4
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 2.0 #was 3
 feasibility_check_no_poses: 5
    
 # Robot
         
 max_vel_x: 1.2
 max_vel_x_backwards: 0
 max_vel_y: 0
 max_vel_theta: 0.8
 acc_lim_x: 0.5
 acc_lim_theta: 0.6
 min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

#  footprint_model:
#    type: "point"


 footprint_model:
    type: "polygon"
    vertices: [[-0.70, -0.42], [-0.7, 0.42], [0.55, 0.42], [0.55, -0.42]] # for type "polygon"
 # GoalTolerance

#  goal_plan_viapoint_sep: 3 # intersection points on the global path with TEB in meters
 xy_goal_tolerance: 2
 yaw_goal_tolerance: 0.3
 free_goal_vel: false
    
 # Obstacles
    
 min_obstacle_dist: 0.5 #was 0.4 # This value must also include our robot radius, since footprint_model is set to "point".
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 10 #30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5
 controller_frequency: 50 #was 5
 # Optimization
    
 no_inner_iterations: 2
 no_outer_iterations: 1
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 weight_adapt_factor: 2

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 5
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False